### ISSUE TITLE
Alert "Project Number Mismatch"

### ISSUE THREAD

**Issue by atoyansk** [Lesruez93/Ionic-Cordova-Firebase-Phone-Auth-Android-and-IOS-#1]
All the project is setted up, including all Firebase details (but only in Android for now). The sms code is being sent properly, but when I try to verify it, it displays the alert with the message "Project Number Mismatch". 

One additional detail: I had to install `cordova-plugin-firebasex` instead `cordova-plugin-firebase`, because of [this](https://stackoverflow.com/questions/49183917/failed-to-execute-aapt-with-cordova)

**Comment by boblepepeur** [comment]
same problem

**Comment by pushpraj4131** [comment]
> All the project is setted up, including all Firebase details (but only in Android for now). The sms code is being sent properly, but when I try to verify it, it displays the alert with the message "Project Number Mismatch".
> 
> One additional detail: I had to install `cordova-plugin-firebasex` instead `cordova-plugin-firebase`, because of [this](https://stackoverflow.com/questions/49183917/failed-to-execute-aapt-with-cordova)

Please tell how you solved it. Facing same issue.

**Comment by zawmn** [comment]
I also got the same issue.  what is the solution of this issue?
